version: '3.8'

services:
  postgres:
    image: postgres:latest  # Use a specific version tag for production
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password  # Replace with a stronger password
      - POSTGRES_DB=db  # Replace with your desired database name
    volumes:
      - postgres-data:/var/lib/postgresql/data  # Persistent storage for data

volumes:
  postgres-data: {}  # Define the empty volume
